# Ejercicios

Resuelve los siguientes ejercicios. Recuerda comentar debidamente.

In [9]:
import numpy as np

1. Crea un array de tamaño 3x3 lleno de unos.

In [10]:
# np.ones devuelve un nuevo array del tamaño y tipo dados, rellenado con unos
array = np.ones((3, 3))

print(f"Array:\n{array}\n\nTamaño:{array.shape}")

Array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Tamaño:(3, 3)


2. Crea un array de tamaño 4x4 lleno de ceros del tipo entero.

In [11]:
# numpy.zeros devuelve un nuevo array del tamaño y tipo dados, rellenado con ceros
array = np.zeros((4, 4), dtype=int)

print(f"Array:\n{array}\n\nTamaño:{array.shape}")

Array:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Tamaño:(4, 4)


3. Crea un array de tamaño 2x2 lleno del valor 5.

In [12]:
# np.full devuelve un nuevo array del tamaño y tipo dados, rellenado con el valor proveído.
array = np.full((2, 2), 5)

print(f"Array:\n{array}\n\nTamaño:{array.shape}")

Array:
[[5 5]
 [5 5]]

Tamaño:(2, 2)


4. Crea un array que contenga los números del 1 al 9. Luego, imprime sus atributos ndim, shape y size. Por último, remodela el array en una matriz (3x3).

In [13]:
# numpy.arange devuelve valores equiespaciados dentro de un intervalo dado.
# Crea un array que contenga los números del 1 al 9.
array = np.arange(1, 10)

# Imprimir los atributos ndim, shape y size.
# ndim => Número de dimensiones de la matriz.
# shape => Devuelve una tupla con el tamaño del array.
# size => Número de elementos de la matriz.
print("Array original:")
print(f"Ndim: {array.ndim}\nShape: {array.shape}\nSize: {array.size}")

# Remodelar el array en una matriz (3x3).
print("\n\nArray al remodelar la matriz (3x3):")
array = array.reshape(3, 3)
print(f"Ndim: {array.ndim}\nShape: {array.shape}\nSize: {array.size}")

Array original:
Ndim: 1
Shape: (9,)
Size: 9


Array al remodelar la matriz (3x3):
Ndim: 2
Shape: (3, 3)
Size: 9


5. Crea un array que contenga 10 valores equiespaciados entre 0 y 20. Además, se debe mostrar la razón aritmética (incremento).

In [14]:
# Crea un array que contenga 10 valores equiespaciados entre 0 y 20.
# numpy.linspace devuelve num muestras equiespaciadas, calculadas sobre el intervalo [start, stop].
array = np.linspace(0, 20, num=10, retstep=True)
print(f"Ndim: {array[0].ndim}\nShape: {array[0].shape}\nSize: {array[0].size}")
print(f"\nArray:\n{array[0]}")

Ndim: 1
Shape: (10,)
Size: 10

Array:
[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]


6. Crea una pila de 3 matrices que tengan 2 filas y 3 columnas. Los elementos de la matriz 3D deben ser estar en el orden indicado por los elementos del intervalo [1, 18].

In [15]:
# Crear una lista de números del 1 al 18
array = np.arange(1, 19)

# Redimensionar el array a una matriz 3D con la forma (3, 2, 3)
matriz_3d = array.reshape((3, 2, 3))

print(matriz_3d)
print("\nDimensiones: ", matriz_3d.ndim)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]

Dimensiones:  3


7. Dado un array bidimensional mat, selecciona las filas pares y las columnas impares usando solamente la indexación.

mat = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

In [16]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Seleccionar filas pares y columnas impares
# 1. Utiliza el operador de slicing : para seleccionar todas las filas.
# 2. Usa el operador de slicing con pasos ::2 para seleccionar las filas pares.
# 3. Utiliza el operador de slicing con pasos 1::2 para seleccionar las columnas impares.
result = array[::2, 1::2]

print(result)


[[ 2  4]
 [10 12]]


8. Dada la matriz tensor, selecciona los elementos en las matrices exteriores y en las filas y columnas pares de cada matriz.

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6]],

                   [[7, 8, 9],
                    [10, 11, 12]],

                   [[13, 14, 15],
                    [16, 17, 18]]])



In [17]:
tensor = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])

# Seleccionar matrices exteriores (primera y última), filas pares y
# columnas pares de cada matriz seleccionada
result = tensor[[0, -1], ::2, ::2]

print(result)


[[[ 1  3]]

 [[13 15]]]


9. Crea un array de tamaño 3x3 lleno de números aleatorios enteros entre 1 y 100 y encuentra el valor máximo. Obs: np.max puede resultar útil.

In [18]:
# Crear un array de tamaño 3x3 lleno de números aleatorios enteros entre 1 y 100
# Parámetros de randint: low, high, size, dtype
array = np.random.randint(0, 101, (3, 3))

# Imprimir el valor máximo del array
print(f"El valor máximo del array:\n{array}, es: {np.max(array)}")

El valor máximo del array:
[[ 51  22  73]
 [ 30  22  95]
 [ 58 100  27]], es: 100


10. Cambia la forma de un array de 3x3 lleno del valor 3 a uno de 9x1. Luego, cambia el último elemento del array a 100 (usar índices negativos).


In [19]:
# Crear un array 3x3 lleno del valor 3
array = np.full((3, 3), 3)
print(f"Array 3X3 lleno del valor 3:\n{array}")

# Cambiar la forma del array a 9x1
array = array.reshape((9, 1))
print(f"\nArray 9x1 lleno del valor 3:\n{array}")

# Cambiar el último elemento del array a 100
array[-1] = 100
print(f"\nArray 9x1 con el último valor cambiado:\n{array}")

Array 3X3 lleno del valor 3:
[[3 3 3]
 [3 3 3]
 [3 3 3]]

Array 9x1 lleno del valor 3:
[[3]
 [3]
 [3]
 [3]
 [3]
 [3]
 [3]
 [3]
 [3]]

Array 9x1 con el último valor cambiado:
[[  3]
 [  3]
 [  3]
 [  3]
 [  3]
 [  3]
 [  3]
 [  3]
 [100]]


11. Crea un array 2x3 que contenga 6 elementos equiespaciados dentro del intervalo [8, 12). Luego cree otro array 2x3 con elementos aleatorios del intervalo (20, 30).  Concatena dos arrays pero en su forma unidimensional. Muestra el array resultante y muestra el valor mínimo (np.min).


In [20]:
# Crear un array 2x3 con 6 elementos equiespaciados dentro del intervalo [8, 12)
array1 = np.linspace(8, 12, num=6, endpoint=False).reshape(2, 3)
print(f"Array 1:\n{array1}")

# Crear un array 2x3 con elementos aleatorios del intervalo (20, 30).
array2 = np.random.randint(20, 30, (2, 3))
print(f"\nArray 2:\n{array2}")

# Concatenar los arrays en su forma unidimensional
array = np.concatenate([array1.flatten(), array2.flatten()])

# Mostrar el array resultante
print(f"\nArray resultante:\n{array}")

# Mostrar el valor mínimo
print(f"\nEl valor mínimo del array es: {np.min(array)}")

Array 1:
[[ 8.          8.66666667  9.33333333]
 [10.         10.66666667 11.33333333]]

Array 2:
[[26 21 28]
 [20 22 22]]

Array resultante:
[ 8.          8.66666667  9.33333333 10.         10.66666667 11.33333333
 26.         21.         28.         20.         22.         22.        ]

El valor mínimo del array es: 8.0


12. Crea un array 10x10 con elementos que contengan los primeros 100 números pares. Divide un array unidimensional en tres partes (3x10, 3x10 y 4x10), cada una de las tres partes deben ser guardadas por medio de decompresión de tuplas.

In [21]:
# Crear un array 10x10 con elementos que contengan los primeros 100 números pares
array = np.arange(0, 200, 2).reshape(10, 10)

# Dividir el array en tres partes
a1 = array[:3, :]  # 3x10
a2 = array[3:6, :]  # 3x10
a3 = array[6:, :]   # 4x10

# Guardar cada parte por medio de descompresión de tuplas
a, b, c = a1, a2, a3


print("Parte 1 (3x10):")
print(a)
print("\nParte 2 (3x10):")
print(b)
print("\nParte 3 (4x10):")
print(c)

Parte 1 (3x10):
[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]]

Parte 2 (3x10):
[[ 60  62  64  66  68  70  72  74  76  78]
 [ 80  82  84  86  88  90  92  94  96  98]
 [100 102 104 106 108 110 112 114 116 118]]

Parte 3 (4x10):
[[120 122 124 126 128 130 132 134 136 138]
 [140 142 144 146 148 150 152 154 156 158]
 [160 162 164 166 168 170 172 174 176 178]
 [180 182 184 186 188 190 192 194 196 198]]


13. Crea una matriz 2x3 llena de 0 y otra 1x3 llena de 1. Concatena y muestra la matriz resultante.

In [22]:
# Crear una matrix 2x3 llena de 0
array1 = np.zeros((2, 3), dtype=int)
array2 = np.ones((1, 3), dtype=int)

# Concatenar los dos arrays
array = np.concatenate([array1, array2])

# Mostrar la matriz resultante
print("Matriz resultante:\n", array)

Matriz resultante:
 [[0 0 0]
 [0 0 0]
 [1 1 1]]


14. Escribe código para obtener la submatriz a partir de la matriz original.

Matriz original:
[[ 7  4  2]
 [ 9 10  8]
 [ 3  6  1]]

Submatriz:
[10  8]


In [23]:
# Matriz original
matriz = np.array([[7, 4, 2],
                   [9, 10, 8],
                   [3, 6, 1]])

# Obtener la submatriz [10, 8]
submatriz = matriz[1, 1:3]

print("Submatriz: ", submatriz)

Submatriz:  [10  8]
